name 'log_hello'
maintainer 'Collin McNeese'
maintainer_email 'collin@mydevsandbox.com'
license 'Apache-2.0'
description 'Installs/Configures log_hello'
version '0.1.3'
chef_version '>= 13.0'

issues_url 'https://github.com/collinmcneese/log_hello/issues'
source_url 'https://github.com/collinmcneese/log_hello'
